# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js lts
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Show apt config
      run: |
        cat /etc/apt/sources.list
        cat /etc/apt/sources.list.d/gitlab.list
        cat /etc/apt/sources.list.d/nodesource.list
        cat /etc/apt/sources.list.d/docker.list
        cat /etc/apt/sources.list.d/vbox.list

    - name: Build
      run: |
        npm install --ignore-scripts
        npm run nyc-install-test
        npm run report-coverage
